"""remove_hitl_tables

Revision ID: 17136468099b
Revises: b7f8a9c0d1e2
Create Date: 2026-01-01 19:44:05.256531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '17136468099b'
down_revision: Union[str, Sequence[str], None] = 'b7f8a9c0d1e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hitl_requests_conversation_id'), table_name='hitl_requests')
    op.drop_index(op.f('ix_hitl_requests_status'), table_name='hitl_requests')
    op.drop_index(op.f('ix_hitl_requests_user_id'), table_name='hitl_requests')
    op.drop_table('hitl_requests')
    op.alter_column('oauth_tokens', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('tenant_configs', 'config_value',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('tenants', 'api_key',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('tenants', 'metadata',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tenants', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('tenants', 'api_key',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('tenant_configs', 'config_value',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('oauth_tokens', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.create_table('hitl_requests',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('conversation_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tool_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('tool_args', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('server_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'APPROVED', 'REJECTED', 'EXPIRED', name='hitl_status'), server_default=sa.text("'PENDING'::hitl_status"), autoincrement=False, nullable=False),
    sa.Column('decision_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('decision_reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('hitl_requests_conversation_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('hitl_requests_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('hitl_requests_pkey'))
    )
    op.create_index(op.f('ix_hitl_requests_user_id'), 'hitl_requests', ['user_id'], unique=False)
    op.create_index(op.f('ix_hitl_requests_status'), 'hitl_requests', ['status'], unique=False)
    op.create_index(op.f('ix_hitl_requests_conversation_id'), 'hitl_requests', ['conversation_id'], unique=False)
    # ### end Alembic commands ###
