"""clean_checkpointers

Revision ID: f08c2c086e1b
Revises: a1b2c3d4e5f6
Create Date: 2025-12-23 15:39:19.046981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f08c2c086e1b'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Drop constraints first
    op.drop_constraint(op.f('conversations_user_id_fkey'), 'conversations', type_='foreignkey')
    op.drop_constraint(op.f('conversations_tenant_id_fkey'), 'conversations', type_='foreignkey')
    
    # 2. Drop dependent tables
    op.drop_index(op.f('ix_hitl_approvals_conversation_id'), table_name='hitl_approvals')
    op.drop_index(op.f('ix_hitl_approvals_status'), table_name='hitl_approvals')
    op.drop_index(op.f('ix_hitl_approvals_user_id'), table_name='hitl_approvals')
    op.drop_table('hitl_approvals')

    op.drop_index(op.f('ix_mcp_configurations_server_name'), table_name='mcp_configurations')
    op.drop_index(op.f('ix_mcp_configurations_tenant_id'), table_name='mcp_configurations')
    op.drop_index(op.f('ix_mcp_configurations_user_id'), table_name='mcp_configurations')
    op.drop_table('mcp_configurations')
    
    op.drop_index(op.f('ix_credentials_service_name'), table_name='credentials')
    op.drop_index(op.f('ix_credentials_tenant_id'), table_name='credentials')
    op.drop_index(op.f('ix_credentials_user_id'), table_name='credentials')
    op.drop_table('credentials')

    # 3. Drop users table
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_table('users')
    
    # 4. Drop checkpoint tables
    op.drop_table('checkpoint_migrations')
    op.drop_index(op.f('checkpoint_blobs_thread_id_idx'), table_name='checkpoint_blobs')
    op.drop_table('checkpoint_blobs')
    
    # 5. Alter/Modify remaining tables
    op.alter_column('conversations', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    
    op.alter_column('messages', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.drop_column('messages', 'agent_name')
    op.drop_column('messages', 'token_count')
    op.add_column('tenants', sa.Column('api_key', sa.String(length=255), nullable=True))
    op.add_column('tenants', sa.Column('metadata', sa.JSON(), nullable=True))
    op.alter_column('tenants', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('tenants', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('tenants', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_constraint(op.f('tenants_slug_key'), 'tenants', type_='unique')
    op.create_index(op.f('ix_tenants_api_key'), 'tenants', ['api_key'], unique=True)
    op.create_index(op.f('ix_tenants_is_active'), 'tenants', ['is_active'], unique=False)
    op.drop_column('tenants', 'description')
    op.drop_column('tenants', 'slug')
    op.drop_column('tenants', 'settings')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('tenants', sa.Column('slug', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('tenants', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_tenants_is_active'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_api_key'), table_name='tenants')
    op.create_unique_constraint(op.f('tenants_slug_key'), 'tenants', ['slug'], postgresql_nulls_not_distinct=False)
    op.alter_column('tenants', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('tenants', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('tenants', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_column('tenants', 'metadata')
    op.drop_column('tenants', 'api_key')
    op.add_column('messages', sa.Column('token_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('messages', sa.Column('agent_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.alter_column('messages', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.create_foreign_key(op.f('conversations_user_id_fkey'), 'conversations', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('conversations_tenant_id_fkey'), 'conversations', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.alter_column('conversations', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.create_table('hitl_approvals',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('conversation_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('agent_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('tool_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('tool_arguments', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'APPROVED', 'REJECTED', 'MODIFIED', 'EXPIRED', name='approval_status'), autoincrement=False, nullable=False),
    sa.Column('modified_arguments', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('rejection_reason', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('resolved_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('hitl_approvals_conversation_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('hitl_approvals_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('hitl_approvals_pkey'))
    )
    op.create_index(op.f('ix_hitl_approvals_user_id'), 'hitl_approvals', ['user_id'], unique=False)
    op.create_index(op.f('ix_hitl_approvals_status'), 'hitl_approvals', ['status'], unique=False)
    op.create_index(op.f('ix_hitl_approvals_conversation_id'), 'hitl_approvals', ['conversation_id'], unique=False)
    op.create_table('checkpoint_blobs',
    sa.Column('thread_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('checkpoint_ns', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('channel', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('version', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('blob', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'channel', 'version', name=op.f('checkpoint_blobs_pkey'))
    )
    op.create_index(op.f('checkpoint_blobs_thread_id_idx'), 'checkpoint_blobs', ['thread_id'], unique=False)
    op.create_table('checkpoint_migrations',
    sa.Column('v', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('v', name=op.f('checkpoint_migrations_pkey'))
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('full_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('role', postgresql.ENUM('ADMIN', 'USER', 'VIEWER', name='user_role'), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('api_key', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name='users_tenant_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    sa.UniqueConstraint('api_key', name='users_api_key_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('email', name='users_email_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_table('credentials',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('service_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('encrypted_data', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.Column('label', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('credentials_tenant_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('credentials_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('credentials_pkey')),
    sa.UniqueConstraint('tenant_id', 'user_id', 'service_name', name=op.f('uq_credential_tenant_user_service'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_credentials_user_id'), 'credentials', ['user_id'], unique=False)
    op.create_index(op.f('ix_credentials_tenant_id'), 'credentials', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_credentials_service_name'), 'credentials', ['service_name'], unique=False)
    op.create_table('mcp_configurations',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('server_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('enabled', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('config_override', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('expert_role', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('custom_prompt', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('mcp_configurations_tenant_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('mcp_configurations_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('mcp_configurations_pkey')),
    sa.UniqueConstraint('tenant_id', 'user_id', 'server_name', name=op.f('uq_mcp_config_tenant_user_server'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_mcp_configurations_user_id'), 'mcp_configurations', ['user_id'], unique=False)
    op.create_index(op.f('ix_mcp_configurations_tenant_id'), 'mcp_configurations', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_mcp_configurations_server_name'), 'mcp_configurations', ['server_name'], unique=False)
    # ### end Alembic commands ###
